export const IMAGE_ASSETS = {
    LOGO : "/assets/images/logo/logo-light.png",
    LOGO_SYMBOL : "/assets/images/logo/logo-light-symbol.png",
    SCROLL_TOP : "/assets/images/logo/scroll_top.svg",
    NOT_FOUND: "/assets/404.gif",
    HERO_SECTION_1 : "/assets/images/earth.png",
    HERO_SECTION_2 : "/assets/images/code.png",
    
    SERVICE_IMG :{
        BLOCKCHAIN: "/assets/images/services/blockchain-dev.png",
        CMS_DEV: "/assets/images/services/cms-dev.png",
        CUSTOM_DEV: "/assets/images/services/custom-dev.png",
        ECOMMERCE_DEV: "/assets/images/services/ecommerce-dev.png",
        GRAPHIC_DESIGN: "/assets/images/services/graphic-des.png",
        INVENTORY_DEV: "/assets/images/services/inventory-dev.png",
        JS_DEV: "/assets/images/services/js-dev.png",
        GOOGLE_ADS: "/assets/images/services/google-ads.png",
        META_ADS: "/assets/images/services/meta-ads.png",
        MOBILE_APP_DEV: "/assets/images/services/mobile-app-dev.png",
        UIUX_DESIGN: "/assets/images/services/ui-ux.png",
        WORDPRESS_DEV: "/assets/images/services/wordpress-dev.png",
    },

    TOOLS: [
        "logos:vue",
        "devicon:nextjs",
        "catppuccin:javascript-react",
        "vscode-icons:file-type-angular",
        "devicon:nuxtjs",
        "logos:nodejs-icon-alt",
        "simple-icons:express",
        "devicon:laravel",
        "devicon:dotnetcore",
        "logos:javascript",
        "logos:typescript-icon",
        "devicon:python",
        "devicon:java",
        "devicon:go",
        "simple-icons:rust",
        "devicon:kotlin",
        "devicon:swift",
        "devicon:dart",
        "logos:ruby",
        "vscode-icons:file-type-flutter",
        "devicon:mysql",
        "devicon:postgresql",
        "devicon:mongodb",
        "devicon:redis",
        "mdi:aws",
        "devicon:azure",
        "devicon:googlecloud",
        "vscode-icons:file-type-html",
        "vscode-icons:file-type-css",
        "logos:sass",
        "logos:tailwindcss-icon",
        "devicon:bootstrap",
        "logos:material-ui",
        "devicon:jquery",
        "logos:redux",
        "logos:shopify",
        "devicon:figma",
        "devicon:git",
        "logos:postman-icon",
        "vscode-icons:file-type-solidity",
    ]
    
};

