const BASE_URL = "/assets/images/";
const LOGO_BASE = BASE_URL + "logo/";
const SERVICE_BASE = BASE_URL + "services/";
const TEAM_BASE = BASE_URL + "team/";

export const IMAGE_ASSETS = {
  LOGO: LOGO_BASE + "logo-light.png",
  LOGO_SYMBOL: LOGO_BASE + "logo-light-symbol.png",
  SCROLL_TOP: LOGO_BASE + "scroll_top.svg",
  NOT_FOUND: BASE_URL + "404.gif",
  HERO_SECTION_1: BASE_URL + "earth.png",
  HERO_SECTION_2: BASE_URL + "code.png",

  SERVICE_IMG: {
    BLOCKCHAIN: SERVICE_BASE + "blockchain-dev.png",
    CMS_DEV: SERVICE_BASE + "cms-dev.png",
    CUSTOM_DEV: SERVICE_BASE + "custom-dev.png",
    ECOMMERCE_DEV: SERVICE_BASE + "ecommerce-dev.png",
    GRAPHIC_DESIGN: SERVICE_BASE + "graphic-des.png",
    INVENTORY_DEV: SERVICE_BASE + "inventory-dev.png",
    JS_DEV: SERVICE_BASE + "js-dev.png",
    GOOGLE_ADS: SERVICE_BASE + "google-ads.png",
    META_ADS: SERVICE_BASE + "meta-ads.png",
    MOBILE_APP_DEV: SERVICE_BASE + "mobile-app-dev.png",
    UIUX_DESIGN: SERVICE_BASE + "ui-ux.png",
    WORDPRESS_DEV: SERVICE_BASE + "wordpress-dev.png",
  },

  TOOLS: [
    "logos:vue",
    "devicon:nextjs",
    "catppuccin:javascript-react",
    "vscode-icons:file-type-angular",
    "devicon:nuxtjs",
    "logos:nodejs-icon-alt",
    "simple-icons:express",
    "devicon:laravel",
    "devicon:dotnetcore",
    "logos:javascript",
    "logos:typescript-icon",
    "devicon:python",
    "devicon:java",
    "devicon:go",
    "simple-icons:rust",
    "devicon:kotlin",
    "devicon:swift",
    "devicon:dart",
    "logos:ruby",
    "vscode-icons:file-type-flutter",
    "devicon:mysql",
    "devicon:postgresql",
    "devicon:mongodb",
    "devicon:redis",
    "mdi:aws",
    "devicon:azure",
    "devicon:googlecloud",
    "vscode-icons:file-type-html",
    "vscode-icons:file-type-css",
    "logos:sass",
    "logos:tailwindcss-icon",
    "devicon:bootstrap",
    "logos:material-ui",
    "devicon:jquery",
    "logos:redux",
    "logos:shopify",
    "devicon:figma",
    "devicon:git",
    "logos:postman-icon",
    "vscode-icons:file-type-solidity",
  ],
  
   TEAM : [
    TEAM_BASE + "abhay.png", //1
    TEAM_BASE + "chintanbhai.png",
    TEAM_BASE + "devan.png",
    TEAM_BASE + "dixit.png",
    TEAM_BASE + "ghanshyam.png",
    TEAM_BASE + "jiya.png",
    TEAM_BASE + "kashyap.png",
    TEAM_BASE + "krina.png",
    TEAM_BASE + "krupali.png",
    TEAM_BASE + "miten.png", //10
    TEAM_BASE + "nemisha.png",
    TEAM_BASE + "payal.png",
    TEAM_BASE + "ravibhai.png",
    TEAM_BASE + "rohan.png",
    TEAM_BASE + "shivang.png",
    TEAM_BASE + "taman.png",
    TEAM_BASE + "trushit.png",
    TEAM_BASE + "utsav.png",
    TEAM_BASE + "vansh.png",
    TEAM_BASE + "vishva.png", //20
    TEAM_BASE + "princy.png",
    TEAM_BASE + "aaryan.png",
    TEAM_BASE + "viren.png",
    TEAM_BASE + "chintanbhai.png",
  ]
  
};
