const BASE_URL = "/assets/images/portfolio/";
export const PORTFOLIO_CATEGORY = ["nextjs", "reactjs","nodejs","wordpress", "shopify","blockchain","mobile","uiux", "erp"];
export const PORTFOLIO = [
  {
    title: "Lumetiq",
    slug: "lumetiq",
    tech_category: ["nextjs"],
    project_type: "Elevator Solutions",
    publisher_name: "Lumetiq Industries",
    description: [
      "Our project focuses on delivering innovative and reliable elevator systems that redefine vertical transportation. Designed with cutting-edge technology, our elevators ensure maximum safety, efficiency, and user comfort while meeting the needs of residential, commercial, and industrial spaces. Every solution is engineered to align with the highest global standards, offering smooth, secure, and future-ready performance.",
      "We go beyond just providing elevators — our approach emphasizes personalized solutions and ongoing support to ensure long-term reliability. From modern designs that enhance building aesthetics to smart features that improve operational efficiency, we craft elevator systems that help businesses and communities elevate to new heights with confidence and style.",
    ],
    image_path: BASE_URL + "lumetiq/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.lumetiq.in/",
  },
  {
    title: "Homiqly",
    slug: "homiqly",
    tech_category: ["nextjs", "erp", "uiux"],
    project_type: "Home & Beauty Services Platform",
    publisher_name: "Homiqly",
    description: [
      "Homiqly is a trusted platform for on-demand beauty services, designed to bring skilled professionals directly to customers' doorsteps. By simplifying the process of finding and booking reliable experts, we make self-care more convenient, safe, and personalized. At the same time, the platform empowers professionals to expand their businesses independently through a flexible, user-friendly system that supports growth and financial freedom.",
      "Our focus is on building a seamless and trustworthy experience where quality meets convenience. With verified professionals, transparent bookings, and exceptional service delivery, Homiqly is redefining how people experience beauty and self-care at home. Guided by our mission and vision, we aim to make effortless, reliable home services a reality for everyone.",
    ],
    image_path: BASE_URL + "homiqly/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp", "ss5.webp"],
    project_link: "https://www.homiqly.com/",
  },
  {
    title: "GNext Groups",
    slug: "gnext-groups",
    tech_category: ["reactjs", "uiux"],
    project_type: "Packaging Solutions / Manufacturing",
    publisher_name: "GNext Groups",
    description: [
      "Genext Industries delivers cutting-edge packaging solutions designed to meet the evolving needs of modern businesses across industries. With a strong focus on innovation, sustainability, and quality, our packaging systems are engineered to protect, preserve, and enhance products while ensuring cost-efficiency and environmental responsibility. We provide customized solutions that align with global standards and help brands stand out in a competitive marketplace.",
      "Our project approach emphasizes customer-centric design, advanced technology, and sustainable practices. From concept to completion, we ensure packaging solutions that not only address functional requirements but also contribute to long-term brand growth and environmental stewardship. With a blend of technical expertise and creative innovation, we continue to set new benchmarks in packaging excellence worldwide.",
    ],
    image_path: BASE_URL + "gnext/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.genextgroup.co/",
  },
  {
    title: "Brahmani Lab",
    slug: "brahmani-lab",
    tech_category: ["reactjs"],
    project_type: "Laboratory Instruments & Scientific Solutions",
    publisher_name: "Brahmani Lab",
    description: [
      "We specialize in delivering premium laboratory instruments designed for precision, accuracy, and efficiency. Our solutions support both scientific research and industrial applications, enabling professionals to achieve reliable results with confidence. With a strong focus on innovation and quality, we provide tools that enhance productivity while meeting international standards.",
      "From precision measuring devices to advanced analytical equipment, our products are crafted to serve the diverse needs of modern laboratories. Backed by expertise and dedicated customer support, we aim to empower scientists, researchers, and industries with cutting-edge technology and dependable solutions that drive progress and discovery.",
    ],
    image_path: BASE_URL + "brahmani/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://brahmanilabinstruments.com/",
  },
  {
    title: "Root Labs",
    slug: "root-labs",
    tech_category: ["reactjs"],
    project_type: "Holistic Wellness & Traditional Medicine Supplements",
    publisher_name: "Root Labs",
    description: [
      "Born out of a personal journey toward healing, this project focuses on creating holistic wellness solutions that combine the wisdom of traditional medicine with modern quality standards. Recognizing the limitations of pharmaceutical remedies, the initiative seeks to provide natural, effective alternatives rooted in centuries-old practices while making them accessible to today’s health-conscious community.",
      "By blending eastern medicinal ingredients with rigorous research and high-quality production, the project aims to fill the gap in the wellness industry for safe, reliable, and authentic supplements. The focus is on empowering individuals to take charge of their health through holistic, sustainable, and culturally rooted solutions that prioritize both physical and mental well-being.",
    ],
    image_path: BASE_URL + "rootlabs/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://rootlabs.co/",
  },
  {
    title: "Tante Tina",
    slug: "tante-tina",
    tech_category: ["shopify", "uiux"],
    project_type: "Women’s Health & Wellness Coaching",
    publisher_name: "Aunt Tina",
    description: [
      "Tante Tina is dedicated to empowering women to live a sustainably healthy lifestyle through a holistic focus on gut health, hormone balance, mindfulness, and overall well-being. Drawing from personal experiences with health challenges, the platform is built on empathy, expertise, and a genuine passion for helping women achieve long-term transformation.",
      "With training in nutrition, detoxification, women’s health, and mental health, Tante Tina provides personalized guidance to help women discover the foods, nutrients, and daily routines that truly work for them. More than just coaching, this is a supportive lifestyle approach designed to help women unlock their full physical and mental potential, creating a path toward balance, vitality, and a fulfilling life.",
    ],
    image_path: BASE_URL + "tante-tina/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.tante-tina.com/",
  },
  {
    title: "Quantum Leap Natural Medicine",
    slug: "quantum-leap-natural-medicine",
    tech_category: ["shopify"],
    project_type: "Holistic Nutrition & Integrative Wellness",
    publisher_name: "Quantum Leap Natural Medicine",
    description: [
      "Quantum Leap is a space where science meets spirit in healing, designed to help individuals achieve deep, lasting transformation in body, mind, and energy. Through a blend of bioenergetics, foundational nutrition, and natural practices, we focus on addressing health at the root level rather than just symptoms, creating a path to sustainable well-being. Our approach recognizes that optimal health is everyone’s birthright, and every journey is unique.",
      "Backed by formal training in holistic nutrition, live cell microscopy, and digestive health, along with hands-on clinical experience, Quantum Leap combines knowledge, practice, and passion to deliver impactful results. From nutrient-dense solutions like our specialized bone broths to personalized guidance in nutrition and natural healing, we aim to empower individuals to take control of their wellness. With a balance of expertise, compassion, and innovation, Quantum Leap is redefining what’s possible with holistic health.",
    ],
    image_path: BASE_URL + "quantum-medicine/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://myquantumleap.ca/",
  },
  {
    title: "Renew HR",
    slug: "renew-hr",
    tech_category: ["wordpress"],
    project_type: "HR Technology & Consulting Solutions",
    publisher_name: "SAP Silver Partner",
    description: [
      "Renew HR is dedicated to helping small and mid-sized businesses transform their HR processes through innovation, technology, and deep industry expertise. With senior consulting partners averaging decades of HR and technology experience worldwide, we bring both strategic insights and practical solutions to every client engagement. Our mission is to engage your workforce, renovate employee relationships, and drive organizational transformation, making HR a lever for long-term success.",
      "As a recognized SAP SuccessFactors partner with SAP Recognized Expertise (REx) accreditation, Renew HR delivers solutions built on best practices and proven methodologies. Through affordable HR analytics, qualified partner packages, and tailored consulting services, we make cutting-edge HR innovations accessible to businesses of all sizes. Guided by our purpose and promise, we partner with organizations to achieve digital HR excellence, enabling them to renew, innovate, and grow with confidence.",
    ],
    image_path: BASE_URL + "renew-hr/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.renewhr.com/",
  },
  {
    title: "Scema Construction",
    slug: "scema-construction",
    tech_category: ["reactjs", "nodejs"],
    project_type: "Construction & Infrastructure Development",
    publisher_name: "Scema Construction",
    description: [
      "We specialize in delivering end-to-end construction solutions that combine innovation, precision, and durability. From residential and commercial projects to large-scale infrastructure, our focus is on building spaces that are not only functional but also sustainable. With a strong commitment to safety, quality, and timely delivery, we ensure every project meets the highest industry standards while exceeding client expectations.",
      "Our approach is built on expert engineering, modern technology, and collaborative project management. Whether it’s designing new structures, renovating existing spaces, or developing complex infrastructure, we bring together skilled professionals and advanced techniques to deliver lasting results. At the core of our work lies a passion for shaping environments that inspire growth, connectivity, and a better future.",
    ],
    image_path: BASE_URL + "scema-construction/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "http://www.scemaconstruction.com/",
  },
  {
    title: "Madde And Me",
    slug: "madde-and-me",
    tech_category: ["shopify", "uiux"],
    project_type: "Fashion & Jewelry Design",
    publisher_name: "Madde And Me",
    description: [
      "Maddeandme is built on the vision of making stylish, contemporary jewelry accessible to everyone. In a world where fashion trends change quickly, our collections are carefully curated to stay fresh, modern, and expressive, offering designs that complement every personality and occasion. We believe jewelry should not only enhance natural beauty but also serve as a true extension of self-expression.",
      "Each piece at Maddeandme is crafted as more than just an accessory—it’s a story, a memory, and a reflection of individuality. Our focus is on creating jewelry that resonates emotionally, turning everyday style into an art form. With a balance of creativity, elegance, and timeless charm, Maddeandme helps you celebrate life’s moments while carrying beauty that feels uniquely yours.",
    ],
    image_path: BASE_URL + "madde-and-me/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://maddeandme.com/",
  },
  {
    title: "MINDWHIZ Eduprise",
    slug: "mindwhiz-eduprise",
    tech_category: ["wordpress", "uiux"],
    project_type: "Training & Personal Development Solutions",
    publisher_name: "MINDWHIZ - The Brain Development Eduprise",
    description: [
      "MINDWHIZ specializes in delivering personal development and memory enhancement training programs designed for students, teachers, parents, corporate professionals, and entrepreneurs. What began as a student training and development company has evolved into a platform that empowers individuals across schools, colleges, and corporate environments in India and abroad.",
      "Our programs are built on innovative methodologies and practical techniques that inspire growth, sharpen cognitive abilities, and enhance overall performance. By focusing on confidence, productivity, and lifelong learning skills, MINDWHIZ helps individuals unlock their true potential and achieve excellence in both personal and professional life.",
    ],
    image_path: BASE_URL + "mindwhiz/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://mindwhiz.com/",
  },
  {
    title: "ToyIQ",
    slug: "toy-iq",
    tech_category: ["shopify", "nodejs"],
    project_type: "Toys & Kids Lifestyle Store",
    publisher_name: "ToyIQ",
    description: [
      "ToyiQ is a one-stop destination for fun, learning, and creativity, offering a wide range of toys that inspire imagination and bring joy to every child. From educational games and puzzles to action figures, dolls, and outdoor play essentials, our collection is carefully curated to combine entertainment with development.",
      "We believe toys are more than playthings—they’re tools that help children explore, learn, and grow. At ToyiQ, our mission is to provide safe, high-quality, and innovative toys that spark curiosity, nurture creativity, and create unforgettable childhood memories. Whether for playtime, learning, or gifting, ToyiQ brings happiness to every home.",
    ],
    image_path: BASE_URL + "toyiq/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://toyiq.in/",
  },
  {
    title: "XOOG",
    slug: "xoog",
    tech_category: ["reactjs"],
    project_type: "Toys & Educational Play Solutions",
    publisher_name: "XOOG",
    description: [
      "XOOG is a next-generation toy company dedicated to creating products that inspire fun, creativity, and learning. Our toys are designed to spark imagination while supporting the developmental needs of children across different age groups. From interactive playthings to educational kits, XOOG blends innovation with play to make every moment both exciting and meaningful.",
      "We believe that play is the foundation of growth. That’s why every XOOG product is built with a focus on safety, quality, and engagement, ensuring that children not only enjoy playtime but also gain valuable skills for the future. With XOOG, toys become more than entertainment—they become tools for discovery, creativity, and lifelong learning.",
    ],
    image_path: BASE_URL + "xoog/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "http://www.xoog.info",
  },
  {
    title: "Elisabet Prag",
    slug: "elisabet-prag",
    tech_category: ["shopify", "uiux"],
    project_type: "Jewelry & Lifestyle Accessories",
    publisher_name: "Elisabet Prag",
    description: [
      "Our jewelry is designed to let you wear your passion and express your lifestyle with elegance. Inspired by timeless beauty and modern artistry, each piece is crafted to reflect individuality, confidence, and sophistication. Whether for everyday wear or special occasions, our collections bring together style, meaning, and craftsmanship in every detail.",
      "We believe jewelry is more than an accessory—it’s a statement of personality and a celebration of life’s moments. With designs that blend contemporary trends and classic charm, our mission is to help you elevate your style while carrying a piece of inspiration wherever you go.",
    ],
    image_path: BASE_URL + "elisabet-prag/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://elisabetprag.com/",
  },
  {
    title: "HONEST infotech",
    slug: "honest-infotech",
    tech_category: ["nextjs", "nodejs"],
    project_type: "Web Development & Digital Solutions",
    publisher_name: "HONEST infotech",
    description: [
      "Honest Infotech is a close-knit team of creative designers, developers, marketers, and tech experts passionate about delivering digital solutions that truly make an impact. With a focus on quality over quantity, our 10+ professionals bring together diverse expertise to create flexible, scalable, and result-driven web and marketing solutions tailored to each client’s needs.",
      "We may not be a global giant, but our strength lies in being personal, agile, and committed. Every project is approached with dedication, innovation, and attention to detail—helping businesses grow, strengthen their digital presence, and achieve long-term success. At Honest Infotech, we don’t just build solutions, we build lasting partnerships.",
    ],
    image_path: BASE_URL + "honest-infotech/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://honestinfotech.in/",
  },
  {
    title: "Adore Beds",
    slug: "adore-beds",
    tech_category: ["shopify", "erp"],
    project_type: "Designer Beds & Sleep Solutions",
    publisher_name: "Maison Complete",
    description: [
      "Adore Beds is dedicated to creating stylish, high-quality, and affordable beds that transform your bedroom into a haven of comfort. With a passion for sleep at the core of our philosophy, we design bed frames and sleep solutions that combine modern elegance, durability, and comfort—ensuring that every night ends with a smile.",
      "Our focus is on making good sleep accessible to everyone. By blending smart production methods, timeless design, and premium craftsmanship, Adore Beds delivers products that go beyond furniture—they create an ultimate sleep experience. For us, it’s not just about making beds, it’s about helping you fall in love with sleep all over again.",
    ],
    image_path: BASE_URL + "adore-beds/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://adorebeds.nl/",
  },
  {
    title: "Solana Launcher",
    slug: "solana-launcher",
    tech_category: ["nextjs", "blockchain"],
    project_type: "Blockchain & Token Creation Platform",
    publisher_name: "SolanaLauncher",
    description: [
      "SolanaLauncher.com is a fast and user-friendly platform that enables anyone to create and launch custom SPL tokens on the Solana blockchain in just a few seconds—no coding required. Designed for accessibility, the platform allows users to define key token parameters such as name, symbol, supply, and branding with ease, making token creation possible for individuals and businesses without technical expertise.",
      "Backed by industry-standard security practices, SolanaLauncher ensures a safe and reliable token deployment process. Whether for building decentralized applications (dApps), experimenting with blockchain utilities, or launching community-driven assets, the platform provides a simple, secure, and scalable solution to get tokens live on the Solana blockchain instantly. With responsive support and ongoing innovation, SolanaLauncher is making token creation more accessible than ever before.",
    ],
    image_path: BASE_URL + "solana-launcher/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://solanalauncher.com/",
  },
  {
    title: "Praediumx",
    slug: "praediumx",
    tech_category: ["blockchain"],
    project_type: "Blockchain-Powered Real Estate Investment Platform",
    publisher_name: "PraediumX - Real Estate on Blockchain",
    description: [
      "PraediumX is a blockchain-powered real estate investment platform that leverages the power of blockchain technology to create a transparent, secure, and efficient way to invest in real estate. By using blockchain technology, PraediumX ensures that all transactions are recorded on a secure and transparent ledger, making it easy for investors to track their investments and monitor their returns.",
      "With PraediumX, investors can easily buy, sell, and trade real estate investments with just a few clicks. The platform is designed to be user-friendly and easy to navigate, making it accessible to investors of all skill levels. Whether you're a seasoned investor or a first-time investor, PraediumX has something for everyone.",
    ],
    image_path: BASE_URL + "praediumx/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://praediumx.com/",
  },
  {
    title: "Agrolla Impex",
    slug: "agrolla-impex",
    tech_category: ["nextjs", "nodejs", "uiux"],
    project_type: "Agro Export & Manufacturing Company",
    publisher_name: "Agrolla Impex",
    description: [
      "Agrolla Impex is a distinguished One Star Export House and a trusted manufacturer and exporter of peanuts, oilseeds, grains, and pulses. Headquartered in Gujarat, India, we operate with fully integrated processes that ensure consistency, reliability, and uncompromised quality in every shipment. By combining modern technology with traditional expertise, we deliver agro products that meet the highest global food safety and quality standards.",
      "Our close partnerships with farmers, backed by state-of-the-art processing facilities and rigorous quality control systems, allow us to maintain purity, freshness, and nutritional value across all product lines. With a strong focus on sustainability, ethical sourcing, and global distribution, Agrolla Impex has built a reputation as a preferred supplier for bulk buyers, manufacturers, wholesalers, and retailers worldwide.",
    ],
    image_path: BASE_URL + "agrolla/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.agrollaimpex.com/",
  },
  {
    title: "Gym Master",
    slug: "gym-master",
    tech_category: ["reactjs", "nodejs", "erp", "uiux"],
    project_type: "Membership Management Solution",
    publisher_name: "Treshna Enterprises Ltd.",
    description: [
      "GymMaster is your all-in-one cloud-based business partner, designed to simplify operations and transform the way fitness clubs run. By combining powerful club management software with unmatched customer service, GymMaster streamlines day-to-day tasks, from bookings and billing to marketing and access control, enabling gym owners to focus on growing their business. With flexibility at its core, the system adapts to the unique needs of every club, ensuring seamless integration and tailored solutions for fitness businesses of all sizes.",
      "Backed by Treshna Enterprises, the team behind GymMaster brings decades of innovation and expertise in the fitness industry. From developing purpose-built access control hardware to launching a fully cloud-based solution and mobile app, GymMaster has continuously evolved to meet the demands of a rapidly changing market. Today, thousands of gyms worldwide rely on GymMaster’s cutting-edge technology and dedicated support, making it more than just software—it’s a trusted partner in running and scaling successful fitness clubs.",
    ],
    image_path: BASE_URL + "gymmaster/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.gymmaster.com/",
  },
  {
    title: "MSFG",
    slug: "msfg",
    tech_category: ["nextjs", "nodejs"],
    project_type: "State-Level Memory Sports Championship",
    publisher_name: "Memory Sport Federation of Gujarat",
    description: [
      "The Gujarat Memory Championship (GMC) is the premier platform for memory sports in Gujarat, bringing together athletes from across states to showcase their mental agility. First held in Ahmedabad in 2018, the championship has grown into a benchmark event where participants memorize and recall complex information under strict international guidelines. The 2026 edition will be hosted on 7th June, Sunday, at the Premium Conference Center, Rajkot, running from 8:00 AM to 6:00 PM, with more than 200 participants competing across 4 age categories—Kids, Junior, Adults, and Seniors.",
      "What sets GMC apart is its adherence to international standards, featuring disciplines such as random words, historical dates, binary numbers, random images, and more, each designed to test different memory systems. Beyond competition, the event opens doors for athletes to qualify for international championships, offering them a chance to represent India at the global stage. With live streaming, media coverage, professional judging, and networking opportunities, GMC stands as both a competitive challenge and a platform for career opportunities in memory sports.",
    ],
    image_path: BASE_URL + "msfg/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp"],
    project_link: "https://www.msfg.in/",
  },
  {
    title: "Varsha Foundation",
    slug: "varsha-foundation",
    tech_category: ["reactjs", "nodejs", "erp", "uiux"],
    project_type: "Admin Panel for Non-Profit Management",
    publisher_name: "Varsha Foundation",
    description: [
      "The Varsha Foundation Admin Panel is a secure and user-friendly management system designed to streamline the foundation’s operations and maximize its impact. It allows administrators to manage beneficiary records, track healthcare and educational support, oversee donor contributions, and coordinate staff and volunteers efficiently. With built-in reporting and analytics, the panel ensures transparency and helps assess the effectiveness of ongoing programs.",
      "Through this centralized platform, the foundation can better support children with cancer at its “Home Away from Home” in Lucknow and monitor learning progress at the non-formal education center in Aligarh. By simplifying day-to-day tasks and improving data management, the admin panel strengthens Varsha Foundation’s mission to bring change in childhood cancer care and education for underprivileged children in India.",
    ],
    image_path: BASE_URL + "varsha-foundation/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp", "ss4.webp", "ss5.webp", "ss6.webp"],
    project_link: "https://varshafoundation.org/",
  },
  {
    title: "Judge a Craft",
    slug: "judge-a-craft",
    tech_category: ["shopify"],
    project_type: "Shopify Store",
    publisher_name: "Judge a Craft",
    description: [
      "Judge A Craft is a Shopify store born from Brittnee’s love for handmade creations. What began as a family hobby has grown into a space where customers can easily shop for personalized, meaningful items made with care and creativity.",
      "From custom gifts to school spirit wear, each piece reflects family-inspired passion and attention to detail. Built on Shopify, the store offers a smooth, heartfelt shopping experience that helps people celebrate life’s special moments."
    ],
    image_path: BASE_URL + "judge-a-craft/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp","ss4.webp"],
    project_link: "https://www.judgeacraft.shop/",
  },
  {
    title: "Adore Beds Mobile App",
    slug: "adore-beds-mobile-app",
    tech_category: ["mobile", "erp"],
    project_type: "Designer Beds & Sleep Solutions",
    publisher_name: "Maison Complete",
    description: [
      "Adore Beds is dedicated to creating stylish, high-quality, and affordable beds that transform your bedroom into a haven of comfort. With a passion for sleep at the core of our philosophy, we design bed frames and sleep solutions that combine modern elegance, durability, and comfort—ensuring that every night ends with a smile.",
      "Our focus is on making good sleep accessible to everyone. By blending smart production methods, timeless design, and premium craftsmanship, Adore Beds delivers products that go beyond furniture—they create an ultimate sleep experience. For us, it’s not just about making beds, it’s about helping you fall in love with sleep all over again.",
    ],
    image_path: BASE_URL + "adore-beds-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "https://adorebeds.nl/",
  },
  {
    title: "Movie Ticket Booking Mobile App",
    slug: "movie-ticket-booking-mobile-app",
    tech_category: ["mobile", "uiux"],
    project_type: "Movie Ticket Booking Mobile Application",
    publisher_name: "N/A",
    description: [
      "This mobile app is designed to simplify the movie-going experience by allowing users to browse showtimes, select seats, and book tickets instantly from their smartphones. With a user-friendly interface, real-time availability updates, and multiple payment options, the app ensures a fast, convenient, and hassle-free booking process for movie enthusiasts.",
      "Beyond ticketing, the app provides personalized recommendations, notifications about new releases, and exclusive offers, enhancing the overall entertainment experience. By combining advanced search, secure payments, and interactive features, the app serves as a one-stop solution for movie lovers to plan their outings efficiently while enjoying a seamless digital experience.",
    ],
    image_path: BASE_URL + "movie-ticket-booking-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "#",
  },
  {
    title: "Car Rental Mobile App",
    slug: "car-rental-mobile-app",
    tech_category: ["mobile", "uiux"],
    project_type: "Car Rental Mobile Application",
    publisher_name: "N/A",
    description: [
      "This mobile app is designed to make car rentals simple, fast, and convenient. Users can browse available vehicles, compare prices, choose pickup and drop-off locations, and book cars directly from their smartphones. With real-time availability, secure payment options, and instant confirmations, the app streamlines the car rental process for both short-term and long-term needs.",
    ],
    image_path: BASE_URL + "car-rental-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "#",
  },
  {
    title: "Stock Investment Mobile App",
    slug: "stock-investment-mobile-app",
    tech_category: ["mobile", "uiux"],
    project_type: "Stock Investment & Trading Mobile Application",
    publisher_name: "N/A",
    description: [
      "This mobile app is designed to simplify stock market investing by providing users with a seamless platform to buy, sell, and monitor stocks directly from their smartphones. Featuring real-time market data, portfolio tracking, and secure transactions, the app empowers both beginners and experienced investors to make informed decisions with confidence.",
      "Beyond trading, the app offers personalized insights, market analysis, alerts, and educational resources to help users grow their wealth and manage investments effectively. By combining intuitive design, robust security, and intelligent tools, the app ensures a comprehensive investment experience that makes stock trading accessible, convenient, and efficient for everyone.",
    ],
    image_path: BASE_URL + "stock-investment-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "#",
  },
  {
    title: "Dating Mobile App",
    slug: "dating-mobile-app",
    tech_category: ["mobile", "uiux"],
    project_type: "Dating & Social Connection Mobile Application",
    publisher_name: "N/A",
    description: [
      "This mobile app is designed to connect people and foster meaningful relationships in a safe and engaging environment. Users can create profiles, browse potential matches, chat securely, and discover connections based on shared interests, location, and compatibility. The app combines advanced matching algorithms and intuitive design to make meeting new people simple, enjoyable, and effective.",
      "Beyond connecting singles, the app provides features such as real-time messaging, event suggestions, and personalized recommendations, enhancing the overall social experience. With a focus on safety, privacy, and user engagement, the app empowers individuals to explore friendships, dating, and relationships confidently and conveniently.",
    ],
    image_path: BASE_URL + "dating-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "#",
  },
  {
    title: "Gym Master Mobile App",
    slug: "gym-master-mobile-app",
    tech_category: ["mobile", "erp", "uiux"],
    project_type: "Gym Membership & Fitness Management Mobile Application",
    publisher_name: "Treshna Enterprises Ltd.",
    description: [
      "GymMaster is a comprehensive mobile app designed to streamline gym membership management and enhance the member experience. Users can sign up for memberships, book classes, track attendance, and access personalized workout plans—all from their smartphones. The app also enables gyms to manage member profiles, payments, schedules, and access control efficiently, ensuring smooth day-to-day operations.",
      "Beyond membership management, GymMaster offers features like progress tracking, notifications for upcoming classes, and in-app communication with trainers, creating a fully connected fitness ecosystem. With a focus on convenience, engagement, and fitness goal achievement, GymMaster empowers both gym owners and members to maximize their productivity and results while fostering a seamless, interactive gym experience.",
    ],
    image_path: BASE_URL + "gymmaster-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "https://www.gymmaster.com/",
  },
  {
    title: "Varsha Foundation Mobile App",
    slug: "varsha-foundation-mobile-app",
    tech_category: ["mobile", "erp", "uiux"],
    project_type: "Admin Panel for Non-Profit Management",
    publisher_name: "Varsha Foundation",
    description: [
      "The Varsha Foundation Mobile App is a dedicated platform to connect supporters, volunteers, and beneficiaries with the foundation’s mission. It enables donors to contribute seamlessly, track the impact of their donations, and stay updated with ongoing initiatives like “Home Away from Home” for children with cancer and the non-formal education center in Aligarh. The app also provides real-time updates, stories of change, and event information, ensuring greater transparency and engagement.",
      "For beneficiaries and volunteers, the app acts as a bridge to access resources, request support, and participate in programs. With its simple and user-friendly design, the Varsha Foundation Mobile App empowers communities to stay connected, spread awareness about childhood cancer, and work together toward creating opportunities for underprivileged children across India.",
    ],
    image_path: BASE_URL + "varsha-foundation-mobile/",
    project_images: ["ss1.webp", "ss2.webp", "ss3.webp"],
    project_link: "https://varshafoundation.org/",
  },
  
];
