export const ROUTES = {
    HOME : "/",
    SERVICES : "/services",
    SERVICE_DETAILS : "/service-details",
    PORTFOLIO : "/portfolio",
    PROJECT_DETAILS : "/portfolio-details",
    COURSES : "/corporate-training",
    COURSE_DETAILS : "/corporate-training-details",
    BLOG : "/blog",
    BLOG_DETAILS : "/blog-details",
    ABOUT : "/about",
    CONTACT : "/contact",
    FAQ : "/faq",
    TERMS : "/terms",
    PRIVACY : "/privacy",
}